# A simple workflow to build a wheel + binary for the latest commit.

name: nightly
on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: "3.13"
  UV_VERSION: "0.10.12"

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install uv
        run: $pythonLocation/bin/pip install uv==$UV_VERSION

      - name: Build wheel
        run: uv build

      - name: Delete the old nightly release
        run: |
          gh release delete nightly --cleanup-tag
          sleep 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create nightly release
        uses: softprops/action-gh-release@v2.0.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          tag_name: "nightly"
          draft: false
          fail_on_unmatched_files: true
          name: "nightly"
          files: |
            ./dist/*
