# A quick check to run tests.

name: test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"

env:
  UV_VERSION: "0.10.12"

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.13", "3.14"]
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        id: setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install uv
        run: $pythonLocation/bin/pip install uv==$UV_VERSION

      - name: Install tools
        run: |
          uv tool install pytest
          uv tool install black
          uv tool install isort
          uv tool install ruff

      - name: Run tests
        run: uv run pytest
        env:
          TEST_PROFILES: true

      - name: Run ruff
        run: uv run ruff check .

      - name: Format code.
        run: |
          uv run black --check .
          uv run isort --check .

      - name: Test building
        run: uv build

      - name: Test running the binary
        run: |
          $pythonLocation/bin/pip install dist/*.whl
          yt-community-post-archiver -h
