# A quick check to run tests.

name: test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install Hatch
        uses: pypa/hatch@install
        with:
          version: 1.13.0

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: hatch test

      - name: Test building
        run: hatch build -t wheel

      - name: Test running the binary
        run: |
          pip install dist/*.whl
          yt-community-post-archiver -h
